#!/usr/bin/env python3
"""Write docs/data.js from the study output. The page reads nothing else."""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
DOCS = ROOT / "docs"


def main() -> int:
    name = "results_fit.json" if "--fit" in sys.argv else "results.json"
    results = json.loads((DATA / name).read_text())
    examples = []
    if (DATA / "examples.json").exists():
        examples = json.loads((DATA / "examples.json").read_text())
    DOCS.mkdir(parents=True, exist_ok=True)
    out = (
        "/* generated by study/build_page_data.py, do not edit */\n"
        "const D = " + json.dumps(results, separators=(",", ":")) + ";\n"
        "const EX = " + json.dumps(examples, separators=(",", ":")) + ";\n"
    )
    (DOCS / "data.js").write_text(out)
    kb = len(out) // 1024
    print(f"wrote docs/data.js ({kb} KB) from data/{name}, {len(examples)} example flights")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
