#!/usr/bin/env python3
"""Write docs/data.js from the study output. The page reads nothing else."""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
DOCS = ROOT / "docs"


def main() -> int:
    name = "results_fit.json" if "--fit" in sys.argv else "results.json"
    results = json.loads((DATA / name).read_text())
    examples = []
    if (DATA / "examples.json").exists():
        examples = json.loads((DATA / "examples.json").read_text())

    # The second pass, with the last seconds of every flight removed. Only the
    # parts act four needs travel to the page; the queue and curve of that pass
    # would double the file for nothing.
    for path in sorted(DATA.glob("results_cut*.json")):
        cut = json.loads(path.read_text())
        results["cut"] = {
            "tail_cut": cut.get("tail_cut"),
            "counts": cut.get("counts"),
            "combined": cut.get("combined"),
            "combined_k": cut.get("combined_k"),
            "baselines": cut.get("baselines"),
            "indicators": {
                k: {kk: v[kk] for kk in ("label", "unit", "tier", "threshold", "coverage", "fit", "measure") if kk in v}
                for k, v in (cut.get("indicators") or {}).items()
            },
        }
        break

    DOCS.mkdir(parents=True, exist_ok=True)
    out = (
        "/* generated by study/build_page_data.py, do not edit */\n"
        "const D = " + json.dumps(results, separators=(",", ":")) + ";\n"
        "const EX = " + json.dumps(examples, separators=(",", ":")) + ";\n"
    )
    (DOCS / "data.js").write_text(out)
    kb = len(out) // 1024
    print(f"wrote docs/data.js ({kb} KB) from data/{name}, {len(examples)} example flights")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
